name: Check Test Messages Here

on:
    - push
    - workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.12'
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run basic tests
      id: bastic-test
      run: python -m pytest tests/test_all_lines_in_the_function.py tests/test_grammar.py
    - name: Test results
      id: result-test
      run: python -m pytest -n auto tests/test_results.py
    - name: upload pngs as artifacts
      id: png-artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: plots
        path: ./*.png
        retention-days: 21
        overwrite: true
